In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics

In [2]:
df = pd.read_csv("emails.csv")

In [3]:
df.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [4]:
df.tail()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5 rows x 3002 columns]

In [5]:
df.info

<bound method DataFrame.info of        Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrast

In [6]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [7]:
df.isna().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.drop(['Email No.'],axis=1, inplace=True)

In [10]:
X=df.drop(['Prediction'], axis=1)
y=df['Prediction']

In [11]:
from numpy.random.mtrand import RandomState
from sklearn.preprocessing import scale
X = scale(X)
x_test, x_train, y_train, y_test = train_test_split(X,y,test_size=0.5, random_state=42)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)

In [13]:
print("x_train shape:", x_train.shape)
print("y_train shape:", y_train.shape)

x_train shape: (2586, 3000)
y_train shape: (2586,)


In [14]:
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)

In [15]:
print(y_pred)

[0 0 1 ... 0 1 0]


In [16]:
knn_acc = metrics.accuracy_score(y_test,y_pred)

In [17]:
print(knn_acc)

0.688708430007734


In [18]:
knn_cm = metrics.confusion_matrix(y_test,y_pred)

In [19]:
print(knn_cm)

[[1735   94]
 [ 711   46]]


In [20]:
#cost=1
model = SVC(C=1)
model.fit(x_train,y_train)

SVC(C=1)

In [21]:
y_pred = model.predict(x_test)

In [22]:
svc_cm = metrics.confusion_matrix(y_true = y_test,y_pred = y_pred)
print(svc_cm)

[[1813   16]
 [ 752    5]]


In [23]:
svc_acc = metrics.accuracy_score(y_test,y_pred)
print(svc_acc)

0.703016241299304


In [ ]:
''' This code uses the scikit-learn library to build and evaluate two machine 
learning models for email classification. It begins by loading an email dataset, 
inspecting the data, and cleaning it by removing missing values and unnecessary 
columns. The dataset is split into features (X) and the target variable (y) and then 
scaled for modeling. The code creates a K-Nearest Neighbors (KNN) classifier with 
seven neighbors and a Support Vector Machine (SVM) classifier with a regularization 
parameter (C) set to 1. These models are trained on the training data and evaluated 
on the test data. The code calculates and prints the accuracy and confusion matrix 
for each model to assess their performance in email classification.'''